users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),

]

web_app/urls.py
from django.urls import path, include 
from . import views

app_name = 'web_app'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    #Sales
    path('work_order_forms/', views.work_order_forms, name='work_order_forms'),   # home page for all work order forms 
    path('work_order_forms/<int:work_order_form_number>/', views.work_order_form, name='work_order_form'),   #page for specific work order form
    path('new_work_order_form/', views.new_work_order_form, name='new_work_order_form'), #url for add new work order form

    # Claims
    path('claims/', views.claims, name='claims'),
    path('newclaim/', views.newclaim, name='newclaim'),
    path('viewclaim/<int:claim_number>/', views.viewclaim, name='viewclaim'),
    path('approvedclaims/', views.approvedclaims, name='approvedclaims'),
    path('rejectedclaims/', views.rejectedclaims, name='rejectedclaims'),
    path('validate_vin/', views.validate_vin, name='validate_vin'),

    # Reports
    path('reports/', views.reports, name='reports'),
    path('export-claims-csv/', views.export_claims_csv, name='export_claims_csv'),
    path('export-sales-csv/', views.export_sales_csv, name='export_sales_csv'),
]

web_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('',include('web_app.urls')),
]

web_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


############################################################################ SALES ############################################################################
# Work Orders
class Work_order_form(models.Model):

    # A specific Work Order Form
    #Id field work_order_form_number
    work_order_form_number = models.AutoField(primary_key=True)
    
    date_added = models.DateTimeField(auto_now_add=True) 
    
    product = models.CharField(max_length=200, default='Rust Protection')     #the product that is being sold EX: rust protection, VIN etching
    quantity_used = models.CharField(max_length=200, default=1) 
    payment_amount = models.CharField(max_length=200, default=100) 
    
    customer_name = models.CharField(max_length=200, default='Bob') 
    customer_phone = models.CharField(max_length=200, default='7801234567') 
    vehicle_make = models.CharField(max_length=200, default='Honda') 
    vehicle_vin = models.CharField(max_length=200, default='11111') 
    
    
    
    dealership_name = models.CharField(max_length=200, default = 'Toyota')
    dealership_phone = models.CharField(max_length=200, default = '7801234567')
    contact_name = models.CharField(max_length=200, default='Bob') 
    dealership_email = models.CharField(max_length=200, default = 'dealership@gmail.com')
    address = models.CharField(max_length=200, default = '47 Wallabeye Way') 
    country = models.CharField(max_length=200, default = 'Canada') 
    province = models.CharField(max_length=200, default = 'Alberta') 
    postal_code = models.CharField(max_length=200, default = 'T8V T9C') 
    text = models.CharField(max_length=200)
    

    def __str__(self):
        # Return a string representation of the model
        return f"Work Order Form {self.work_order_form_number}"


############################################################################ CLAIMS ############################################################################

# Claim Model
class Claim(models.Model):
    # Claim Information
    claim_number = models.AutoField(primary_key=True, default=1)
    date_added = models.DateTimeField(auto_now_add=True)

    STATUS_CHOICES = [
        ('status_info', 'Information Only'),
        ('status_pending', 'Pending'),
        ('status_submitted', 'Submitted'),
        ('status_approved', 'Approved'),
        ('status_rejected', 'Rejected'),
        ('status_paid', 'Paid'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='Information Only')

    claim_date = models.DateTimeField(blank=True, default=timezone.now) 
    effective_date = models.DateTimeField(blank=True, default=timezone.now) 
    process_date = models.DateTimeField(blank=True, default=timezone.now) 

    po_num = models.CharField(max_length=200, default='N/A')
    file_num = models.CharField(max_length=200, default='N/A')
    agreement = models.CharField(max_length=200, default='N/A')

    # Aprroval Information
    claim_approvedby = models.CharField(max_length=50, blank=True)
    claim_approvedto = models.CharField(max_length=50, blank=True)
    claim_approved_date = models.DateTimeField(blank=True, null=True, default='') 

    # Rejected Information
    claim_rejectedby = models.CharField(max_length=50, blank=True)
    claim_rejection_date = models.DateTimeField(blank=True, null=True, default='') 
    claim_rejection_reason = models.CharField(max_length=1000, blank=True)

    # Repair Shop Information
    shop_active = models.BooleanField(default=False)
    shop_name = models.CharField(max_length=200, default='N/A')
    shop_phone = models.CharField(max_length=12, default='123-456-7890')
    shop_contact = models.CharField(max_length=200, blank=True)
    shop_email = models.EmailField(blank=True)
    shop_address = models.CharField(max_length=200, default='1234 Main St')
    shop_address2 = models.CharField(max_length=200, blank=True)

    COUNTRY_CHOICES = [
        ('CAN', 'Canada'),
    ]
    shop_country = models.CharField(max_length=50, choices=COUNTRY_CHOICES, default='CAN')
   
    PROVINCE_CHOICES = [
        ('AB', 'Alberta'),
        ('BC', 'British Columbia'),
        ('MB', 'Manitoba'),
        ('NB', 'New Brunswick'),
        ('NL', 'Newfoundland and Labrador'),
        ('NT', 'Northwest Territories'),
        ('NS', 'Nova Scotia'),
        ('NU', 'Nunavut'),
        ('ON', 'Ontario'),
        ('PE', 'Prince Edward Island'),
        ('QC', 'Quebec'),
        ('SK', 'Saskatchewan'),
        ('YT', 'Yukon'),
    ]
    shop_province = models.CharField(max_length=50, choices=PROVINCE_CHOICES, default='Ontario')

    shop_postalcode = models.CharField(max_length=7, default='A1A 1A1')

    # Customer Information
    cust_fname = models.CharField(max_length=30, default='N/A')
    cust_lname = models.CharField(max_length=30, default='N/A')

    policy_type = models.CharField(max_length=50, default='N/A')
    coverage_type = models.CharField(max_length=50, default='N/A')
    vin = models.CharField(max_length=30, default='JTHBP262495004947')

    # Claim Details
    claim_details = models.CharField(max_length=1000, blank=True)

    # Estimate Information
    claim_estimate1 = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    claim_estimate2 = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    claim_req_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    est_tier2 = models.BooleanField(default=False)

    claim_estimate3 = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    claim_estimate4 = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    claim_estimate5 = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)


    # Amount Information
    claim_amt_agreed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    claim_deductible = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    claim_net_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0.00)
    
    # Payment Information
    cheque_num = models.CharField(max_length=50, blank=True)
    cheque_pay_to = models.CharField(max_length=50, blank=True)
    cheque_date = models.DateTimeField(blank=True, null=False, default='') 
    cheque_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def save(self, *args, **kwargs):
        # Convert empty strings to None before saving
        if not self.claim_estimate1:
            self.claim_estimate1 = 0.00
        if not self.claim_estimate2:
            self.claim_estimate2 = 0.00
        if not self.claim_estimate3:
            self.claim_estimate3 = 0.00
        if not self.claim_estimate4:
            self.claim_estimate4 = 0.00
        if not self.claim_estimate5:
            self.claim_estimate5 = 0.00
        if not self.claim_net_amt:
            self.claim_net_amt = 0.00
        if not self.cheque_amt:
            self.cheque_amt = 0.00
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Claim {self.claim_number}"
    
# Claim Problem Model
class Problem(models.Model):
    prob_id = models.AutoField(primary_key=True)
    claim_number = models.ForeignKey(Claim, on_delete=models.CASCADE, related_name='problems')

    # Problem Information
    PROBLEM_TYPE_CHOICES = [
        ('prob_fabric', 'Fabirc'),
        ('prob_leathvin', 'Leather/Vinyl'),
        ('prob_paint', 'Paint'),
        ('prob_rust', 'Rust'),
        ('prob_theft', 'Theft'),
        ('prob_undercoat', 'Undercoat'),
    ]
    prob_type = models.CharField(max_length=30, choices=PROBLEM_TYPE_CHOICES, default='Fabric')

    prob_description = models.TextField(default='N/A')
    prob_part = models.CharField(max_length=50, default='N/A')

    PROBLEM_SIDE_CHOICES = [
        ('prob_bothsides', 'Both'),
        ('prob_leftside', 'Left'),
        ('prob_rightside', 'Right'),
        ('prob_noside', 'N/A'),
    ]
    prob_side = models.CharField(max_length=30, choices=PROBLEM_SIDE_CHOICES, default='N/A')

    goodwill = models.DecimalField(max_digits=7, decimal_places=2, null=True, default=0.00)

    def __str__(self):
        return f"Problem {self.prob_id}"


############################################################################ REPORTS ############################################################################

# Sale Model for Reports
class Sale(models.Model):
    car_dealership = models.CharField(max_length=100)
    daily_sales = models.IntegerField()
    total_revenue = models.DecimalField(max_digits=10, decimal_places=2)

# Claim Model for Reports
class ClaimReport(models.Model):
    number_of_claims = models.IntegerField()

web_app/forms.py
from django import forms
from .models import Claim, Problem, Work_order_form 
from django.forms import inlineformset_factory

############################################################################ SALES ############################################################################

class Work_order_form_form(forms.ModelForm):
    work_order_form_number = forms.IntegerField(widget=forms.HiddenInput())
    class Meta:
        model = Work_order_form
        fields = ['work_order_form_number','product', 'quantity_used', 'payment_amount', 'customer_name', 'customer_phone', 'vehicle_make', 'vehicle_vin', 'dealership_name', 'dealership_phone', 'contact_name', 'dealership_email', 'address', 'country', 'province', 'postal_code']
        labels = {'dealership_name': 'Dealership Name', 'product': 'Product Name', 'customer_name': 'Customer Name', 'customer_phone': 'Customer Phone', 'vehicle_make': 'Vehicle Make', 'vehicle_vin': 'Vehicle VIN', 'dealership_phone': 'Dealership Phone', 'contact_name': 'Contact Name', 'dealership_email': 'Dealership Email', 'postal_code': 'Postal Code'}
        
        def __init__(self, *args, **kwargs):
                super().__init__(*args, **kwargs)
                self.fields['work_order_form_number'].widget.attrs['readonly'] = True  


############################################################################ CLAIMS ############################################################################

class ClaimForm(forms.ModelForm):
    claim_date = forms.DateTimeField(input_formats=['%B %d, %Y'])
    problem_formset = inlineformset_factory(Claim, Problem, fields=('prob_type', 'prob_description', 'prob_part', 'prob_side', 'goodwill'))

    class Meta:
        model = Claim
        fields = '__all__' 

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['claim_approvedby'].required = False
        self.fields['claim_approvedto'].required = False
        self.fields['claim_approved_date'].required = False
        self.fields['claim_rejectedby'].required = False
        self.fields['claim_rejection_date'].required = False
        self.fields['claim_rejection_reason'].required = False

    def clean(self):
        cleaned_data = super().clean()
        status = cleaned_data.get('status')

        if status == 'Approved':
            if not cleaned_data.get('claim_approvedby'):
                self.add_error('claim_approvedby', 'This field is required.')
            if not cleaned_data.get('claim_approvedto'):
                self.add_error('claim_approvedto', 'This field is required.')
            if not cleaned_data.get('claim_approved_date'):
                self.add_error('claim_approved_date', 'This field is required.')
        
        if status == 'Rejected':
            if not cleaned_data.get('claim_rejectedby'):
                self.add_error('claim_rejectedby', 'This field is required.')
            if not cleaned_data.get('claim_rejection_date'):
                self.add_error('claim_rejection_date', 'This field is required.')
            if not cleaned_data.get('claim_rejection_reason'):
                self.add_error('claim_rejection_reason', 'This field is required.')

        return cleaned_data
  
class ProblemForm(forms.ModelForm):
    class Meta:
        model = Problem
        fields = ('prob_type', 'prob_description', 'prob_part', 'prob_side', 'goodwill')
        exclude = ('prob_id',)

web_app/templates/web_app/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
<!--
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
-->

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous">

<!-- jQuery library -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>

<!-- Popper.js library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>

<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

<!-- Required Bootstrap CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- Required jQuery and Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js"></script>


<!--Bootstrap Navbar for Web App-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'web_app:index'%}">C3 Portal</a> <!-- THIS WILL PROBABLY HAVE TO CHANGE ONCE AUTHORIZATION PAGES GET ADDED -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'web_app:work_order_forms'%}">Sales</a>
            </div>
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'web_app:claims'%}">Claims</a>
            </div>
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'web_app:reports'%}">Reports</a>
            
            {% if user.is_authenticated %}
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'users:logout'%}">Logout</a></div>
            {% else %}
                <div class="navbar-nav">
                 <a class="nav-link" href="{% url 'users:login'%}">Login</a></div>
                 <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'users:register'%}">Register</a></div>
            {% endif %}
        
            </div>
        </div>
    </div>
</nav>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>C3 Portal</title>  

    {% load static %}  
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}"> 
    <script src="{% static 'bootstrap.js' %}"></script>
    
</head>  

<body>  

{% block content %} to be overridden
{% endblock content %}
</body>  

</html>

web_app/templates/web_app/viewclaim.html
{% extends 'web_app/base.html' %}
{% block content %}
  
<br>
  <!-- Navigation Tabs, source: https://getbootstrap.com/docs/4.0/components/navbar/ -->

  <ul class="nav nav-tabs">
    <li class="nav-item" role="presentation">
      <a class="nav-link" href="{% url 'web_app:claims'%}">All Claims</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" href="{% url 'web_app:newclaim'%}">New Claim</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link active" href="{% url 'web_app:viewclaim' viewclaim.claim_number %}">View Claim {{ viewclaim.claim_number }}</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link disabled" href="Policies">Policies</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link disabled" href="Warranties">Warranties</a>
    </li>
  </ul>


  <br>
  
  <div class="container">
    <h1>Claim {{ viewclaim.claim_number }}</h1>
    <h2 style="font-size: 25px; margin-top: 20px;">Claim Information</h2>
    <hr>

        <h3 style="font-size: 21px;">Date Added:</h3>
        <p>{{ viewclaim.date_added|date:"F j, Y" }}</p>
        <h3 style="font-size: 21px;">Status:</h3>
        {% if viewclaim.status == "status_rejected" %}
        <p style="color: red">{{ viewclaim.get_status_display }}</p>
        {% elif viewclaim.status == "status_paid" %}
        <p style="color: green">{{ viewclaim.get_status_display }}</p>
        {% else %}
            <p>{{ viewclaim.get_status_display }}</p>
        {% endif %}
        <h3 style="font-size: 21px;">Claim Date:</h3>
        <p>{{ viewclaim.date_added|date:"F j, Y" }}</p>

        {% if viewclaim.status == "status_approved" %}
        <h3 style="font-size: 21px;">Approved By:</h3>
        <p>{{ viewclaim.claim_approvedby|default:" " }}</p>
        <h3 style="font-size: 21px;">Approved To:</h3>
        <p>{{ viewclaim.claim_approvedto|default:" " }}</p>
        <h3 style="font-size: 21px;">Approved Date:</h3>
        <p>{% if viewclaim.status != "status_approved" %} {% else %}{{ viewclaim.claim_approved_date|date:"F j, Y" }}{% endif %}</p>

        {% elif viewclaim.status == "status_rejected" %}
        <h3 style="font-size: 21px;">Rejected By:</h3>
        <p>{{ viewclaim.claim_rejectedby|default:" " }}</p>
        <h3 style="font-size: 21px;">Rejection Date:</h3>
        <p>{% if viewclaim.status != "status_rejected" %} {% else %}{{ viewclaim.claim_rejection_date|date:"F j, Y" }}{% endif %}</p>
        <h3 style="font-size: 21px;">Reason for Rejection:</h3>
        <p>{{ viewclaim.claim_rejection_reason|default:" " }}</p>
        {% endif %}

        <h3 style="font-size: 21px;">Claim Date:</h3>
        <p>{{ viewclaim.claim_date|date:"F j, Y" }}</p>
        <h3 style="font-size: 21px;">Effective Date:</h3>
        <p>{{ viewclaim.effective_date|date:"F j, Y" }}</p>
        <h3 style="font-size: 21px;">Process Date:</h3>
        <p>{{ viewclaim.process_date|date:"F j, Y" }}</p>
        <h3 style="font-size: 21px;">PO #:</h3>
        <p>{{ viewclaim.po_num }}</td>
        <h3 style="font-size: 21px;">File #:</h3>
        <p>{{ viewclaim.file_num }}</p>
        <h3 style="font-size: 21px;">Agreement #:</h3>
        <p>{{ viewclaim.agreement }}</p>

        <br>
        <h2 style="font-size: 25px; margin-top: 20px;">Repair Shop Information</h2>
        <hr>
        <h3 style="font-size: 21px;">Active:</h3>
        <p>{% if viewclaim.shop_active %}YES{% else %}NO{% endif %}</p>
        <h3 style="font-size: 21px;">Shop Name:</h3>
        <p>{{ viewclaim.shop_name }}</p>
        <h3 style="font-size: 21px;">Phone Number:</h3>
        <p>{{ viewclaim.shop_phone }}</p>
        <p>{% if viewclaim.shop_contact == "" %}{% else %}<h3 style="font-size: 21px;">Contact Name:</h3>{{ viewclaim.shop_contact|default:" " }}{% endif %}</p>
        <p>{% if viewclaim.shop_email == "" %}{% else %}<h3 style="font-size: 21px;">Email:</h3>{{ viewclaim.shop_email|default:" " }}{% endif %}</p>
        <h3 style="font-size: 21px;">Address:</h3>
        <p>{{ viewclaim.shop_address }}</p>
        <p>{% if viewclaim.shop_address2 == "" %}{% else %}<h3 style="font-size: 21px;">Address 2:</h3>{{ viewclaim.shop_address2|default:" " }}{% endif %}</p>
        <h3 style="font-size: 21px;">Country:</h3>
        <p>{{ viewclaim.shop_country }}</p>
        <h3 style="font-size: 21px;">Province/Territory:</h3>
        <p>{{ viewclaim.shop_province }}</p>
        <h3 style="font-size: 21px;">Postal Code:</h3>
        <p>{{ viewclaim.shop_postalcode }}</p>

        <br>
        <h2 style="font-size: 25px; margin-top: 20px;">Customer Information</h2>
        <hr>
        <h3 style="font-size: 21px;">First Name:</h3>
        <p>{{ viewclaim.cust_fname }}</p>
        <h3 style="font-size: 21px;">Last Name:</h3>
        <p>{{ viewclaim.cust_lname }}</p>
        <h3 style="font-size: 21px;">Policy Type:</h3>
        <p>{{ viewclaim.policy_type }}</p>
        <h3 style="font-size: 21px;">Coverage Type:</h3>
        <p>{{ viewclaim.coverage_type }}</p>
        <h3 style="font-size: 21px;">Vehicle VIN:</h3>
        <p>{{ viewclaim.vin }}</p>

        <br>
        <h2 style="font-size: 25px; margin-top: 20px;">Problem</h2>
        <hr>
        <p>{{ viewclaim.claim_details }}</td>
        <br>

        {% if viewclaim.claim_req_amt != 0 or viewclaim.claim_estimate1 != 0 or viewclaim.claim_estimate2 != 0 or viewclaim.claim_estimate3 != 0 or viewclaim.claim_estimate4 != 0 or viewclaim.claim_estimate5 != 0 %}
        <br><h2 style="font-size: 25px; margin-top: 20px;">Estimates</h2><hr>
        {% endif %}
        <p>{% if viewclaim.claim_req_amt == 0 %}{% else %}<h3 style="font-size: 21px;">Requested:</h3>${{ viewclaim.claim_req_amt|default:" " }}{% endif %}</p>
        <p>{% if viewclaim.claim_estimate1 == 0 %}{% else %}<h3 style="font-size: 21px;">Estimate #1:</h3>${{ viewclaim.claim_estimate1|default:" " }}{% endif %}</p>
        <p>{% if viewclaim.claim_estimate2 == 0 %}{% else %}<h3 style="font-size: 21px;">Estimate #2:</h3>${{ viewclaim.claim_estimate2|default:" " }}{% endif %}</p>
        <p>{% if viewclaim.claim_estimate3 == 0 %}{% else %}<h3 style="font-size: 21px;">Estimate #3:</h3>${{ viewclaim.claim_estimate3|default:" " }}{% endif %}</p>
        <p>{% if viewclaim.claim_estimate4 == 0 %}{% else %}<h3 style="font-size: 21px;">Estimate #4:</h3>${{ viewclaim.claim_estimate4|default:" " }}{% endif %}</p>
        <p>{% if viewclaim.claim_estimate5 == 0 %}{% else %}<h3 style="font-size: 21px;">Estimate #5:</h3> ${{viewclaim.claim_estimate5|default:" " }}{% endif %}</p>


        <p>{% if viewclaim.claim_amt_agreed == 0 %}{% else %}<br><h2 style="font-size: 25px; margin-top: 20px;">Actual Claim Amount</h2>
            <hr><h3 style="font-size: 21px;">Agreed Amount:</h3>${{ viewclaim.claim_amt_agreed|default:" " }}{% endif %}</p>
        <p>{% if viewclaim.claim_deductible == 0 %}{% else %}<h3 style="font-size: 21px;">Deductible:</h3>${{ viewclaim.claim_deductible|default:" " }}{% endif %}</p>
        <p>{% if viewclaim.claim_net_amt == 0 %}{% else %}<h3 style="font-size: 21px;">Net Amount:</h3>${{ viewclaim.claim_net_amt|default:" " }}{% endif %}</p>
        
        <p>{% if viewclaim.cheque_num == "" %}{% else %}<br><h2 style="font-size: 25px; margin-top: 20px;">Payment Information</h2>
            <hr><h3 style="font-size: 21px;">Cheque #:</h3><p>{{ viewclaim.cheque_num|default:" " }}</p>{% endif %}</p>
        <p>{% if viewclaim.cheque_pay_to == "" %}{% else %}<h3 style="font-size: 21px;">Pay To:</h3>{{ viewclaim.cheque_pay_to|default:" " }}{% endif %}</p>
        <p>{% if viewclaim.cheque_amt == 0 %}{% else %}<h3 style="font-size: 21px;">Cheque Date:</h3>{{ viewclaim.cheque_date|date:"F j, Y" }}{% endif %}</p>
        <p>{% if viewclaim.cheque_amt == 0 %}{% else %}<h3 style="font-size: 21px;">Cheque Amount:</h3>${{ viewclaim.cheque_amt|default:"N/A" }}{% endif %}</p>
        <br>
        <br>
</div>


{% endblock %}
  
  
  

  